/*
  # Add Visualization HTML and Astra Response to Team Dashboard Snapshots

  1. New Columns
    - `visualization_html` (text) - Stores the generated HTML/CSS dashboard visualization from Gemini 3 Flash
    - `astra_raw_response` (jsonb) - Stores the raw response from Astra Intelligence Agent for debugging
    - `generation_version` (text) - Tracks which generation pipeline was used (v1 = direct Gemini, v2 = Astra + Gemini)

  2. Purpose
    - Enable the new two-stage dashboard generation pipeline
    - Store visual dashboard as HTML for rendering in frontend
    - Maintain audit trail of AI responses for debugging and improvement
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'team_dashboard_snapshots' AND column_name = 'visualization_html'
  ) THEN
    ALTER TABLE team_dashboard_snapshots ADD COLUMN visualization_html text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'team_dashboard_snapshots' AND column_name = 'astra_raw_response'
  ) THEN
    ALTER TABLE team_dashboard_snapshots ADD COLUMN astra_raw_response jsonb;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'team_dashboard_snapshots' AND column_name = 'generation_version'
  ) THEN
    ALTER TABLE team_dashboard_snapshots ADD COLUMN generation_version text DEFAULT 'v1';
  END IF;
END $$;

COMMENT ON COLUMN team_dashboard_snapshots.visualization_html IS 'HTML/CSS dashboard visualization generated by Gemini 3 Flash';
COMMENT ON COLUMN team_dashboard_snapshots.astra_raw_response IS 'Raw JSON response from Astra Intelligence Agent';
COMMENT ON COLUMN team_dashboard_snapshots.generation_version IS 'Pipeline version: v1 = direct Gemini, v2 = Astra + Gemini';